// <auto-generated />
using System;
using CorrecoesMgr.Api;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CorrecoesMgr.Api.Migrations
{
    [DbContext(typeof(CorrecoesMgrContext))]
    [Migration("20221013143115_SeedValorModulo")]
    partial class SeedValorModulo
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.10");

            modelBuilder.Entity("CorrecoesMgr.Domain.Correcao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Curso")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Data")
                        .HasColumnType("TEXT");

                    b.Property<string>("NomeAluno")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("NumModulo")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Observacao")
                        .HasColumnType("TEXT");

                    b.Property<string>("Resposta")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Correcoes");
                });

            modelBuilder.Entity("CorrecoesMgr.Domain.ValorModulo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Curso")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("NumModulo")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Valor")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("ValoresModulo");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Curso = "Backend Java",
                            NumModulo = 1,
                            Tipo = "Tarefa do módulo",
                            Valor = 15
                        },
                        new
                        {
                            Id = 2,
                            Curso = "Backend Java",
                            NumModulo = 2,
                            Tipo = "Tarefa do módulo",
                            Valor = 15
                        },
                        new
                        {
                            Id = 3,
                            Curso = "Backend Java",
                            NumModulo = 3,
                            Tipo = "Tarefa do módulo",
                            Valor = 15
                        },
                        new
                        {
                            Id = 4,
                            Curso = "Backend Java",
                            NumModulo = 4,
                            Tipo = "Tarefa do módulo",
                            Valor = 15
                        },
                        new
                        {
                            Id = 5,
                            Curso = "Backend Java",
                            NumModulo = 5,
                            Tipo = "Tarefa do módulo",
                            Valor = 15
                        },
                        new
                        {
                            Id = 6,
                            Curso = "Backend Java",
                            NumModulo = 6,
                            Tipo = "Tarefa do módulo",
                            Valor = 15
                        },
                        new
                        {
                            Id = 7,
                            Curso = "Backend Java",
                            NumModulo = 7,
                            Tipo = "Tarefa do módulo",
                            Valor = 15
                        },
                        new
                        {
                            Id = 8,
                            Curso = "Backend Java",
                            NumModulo = 8,
                            Tipo = "Tarefa do módulo",
                            Valor = 15
                        },
                        new
                        {
                            Id = 9,
                            Curso = "Backend Java",
                            NumModulo = 9,
                            Tipo = "Tarefa do módulo",
                            Valor = 15
                        },
                        new
                        {
                            Id = 10,
                            Curso = "Backend Java",
                            NumModulo = 10,
                            Tipo = "Tarefa do módulo",
                            Valor = 15
                        },
                        new
                        {
                            Id = 11,
                            Curso = "Backend Java",
                            NumModulo = 11,
                            Tipo = "Tarefa do módulo",
                            Valor = 15
                        },
                        new
                        {
                            Id = 12,
                            Curso = "Backend Java",
                            NumModulo = 12,
                            Tipo = "Tarefa do módulo",
                            Valor = 15
                        },
                        new
                        {
                            Id = 13,
                            Curso = "Backend Java",
                            NumModulo = 13,
                            Tipo = "Tarefa do módulo",
                            Valor = 15
                        },
                        new
                        {
                            Id = 14,
                            Curso = "Backend Java",
                            NumModulo = 14,
                            Tipo = "Tarefa do módulo",
                            Valor = 15
                        },
                        new
                        {
                            Id = 15,
                            Curso = "Backend Java",
                            NumModulo = 15,
                            Tipo = "Tarefa do módulo",
                            Valor = 15
                        },
                        new
                        {
                            Id = 16,
                            Curso = "Backend Java",
                            NumModulo = 16,
                            Tipo = "Tarefa do módulo",
                            Valor = 15
                        },
                        new
                        {
                            Id = 17,
                            Curso = "Backend Java",
                            NumModulo = 17,
                            Tipo = "Tarefa do módulo",
                            Valor = 15
                        },
                        new
                        {
                            Id = 18,
                            Curso = "Backend Java",
                            NumModulo = 18,
                            Tipo = "Tarefa do módulo",
                            Valor = 15
                        },
                        new
                        {
                            Id = 19,
                            Curso = "Backend Java",
                            NumModulo = 19,
                            Tipo = "Tarefa do módulo",
                            Valor = 15
                        },
                        new
                        {
                            Id = 20,
                            Curso = "Backend Java",
                            NumModulo = 20,
                            Tipo = "Tarefa do módulo",
                            Valor = 15
                        },
                        new
                        {
                            Id = 21,
                            Curso = "Backend Java",
                            NumModulo = 21,
                            Tipo = "Tarefa do módulo",
                            Valor = 15
                        },
                        new
                        {
                            Id = 22,
                            Curso = "Backend Java",
                            NumModulo = 22,
                            Tipo = "Tarefa do módulo",
                            Valor = 15
                        },
                        new
                        {
                            Id = 23,
                            Curso = "Backend Java",
                            NumModulo = 23,
                            Tipo = "Tarefa do módulo",
                            Valor = 15
                        },
                        new
                        {
                            Id = 24,
                            Curso = "Backend Java",
                            NumModulo = 24,
                            Tipo = "Tarefa do módulo",
                            Valor = 15
                        },
                        new
                        {
                            Id = 25,
                            Curso = "Backend Java",
                            NumModulo = 25,
                            Tipo = "Tarefa do módulo",
                            Valor = 15
                        },
                        new
                        {
                            Id = 26,
                            Curso = "Backend Java",
                            NumModulo = 26,
                            Tipo = "Tarefa do módulo",
                            Valor = 15
                        },
                        new
                        {
                            Id = 27,
                            Curso = "Backend Java",
                            NumModulo = 27,
                            Tipo = "Tarefa do módulo",
                            Valor = 15
                        },
                        new
                        {
                            Id = 28,
                            Curso = "Backend Java",
                            NumModulo = 28,
                            Tipo = "Tarefa do módulo",
                            Valor = 15
                        },
                        new
                        {
                            Id = 29,
                            Curso = "Backend Java",
                            NumModulo = 29,
                            Tipo = "Tarefa do módulo",
                            Valor = 18
                        },
                        new
                        {
                            Id = 30,
                            Curso = "Backend Java",
                            NumModulo = 30,
                            Tipo = "Tarefa do módulo",
                            Valor = 15
                        },
                        new
                        {
                            Id = 31,
                            Curso = "Backend Java",
                            NumModulo = 31,
                            Tipo = "Tarefa do módulo",
                            Valor = 15
                        },
                        new
                        {
                            Id = 32,
                            Curso = "Backend Java",
                            NumModulo = 32,
                            Tipo = "Tarefa do módulo",
                            Valor = 15
                        },
                        new
                        {
                            Id = 33,
                            Curso = "Backend Java",
                            NumModulo = 33,
                            Tipo = "Tarefa do módulo",
                            Valor = 15
                        },
                        new
                        {
                            Id = 34,
                            Curso = "Backend Java",
                            NumModulo = 34,
                            Tipo = "Tarefa do módulo",
                            Valor = 15
                        },
                        new
                        {
                            Id = 35,
                            Curso = "Backend Java",
                            NumModulo = 35,
                            Tipo = "Tarefa do módulo",
                            Valor = 15
                        },
                        new
                        {
                            Id = 36,
                            Curso = "Backend Java",
                            NumModulo = 36,
                            Tipo = "Tarefa do módulo",
                            Valor = 15
                        },
                        new
                        {
                            Id = 37,
                            Curso = "Backend Java",
                            NumModulo = 37,
                            Tipo = "Tarefa do módulo",
                            Valor = 15
                        },
                        new
                        {
                            Id = 38,
                            Curso = "Backend Java",
                            NumModulo = 38,
                            Tipo = "Tarefa do módulo",
                            Valor = 15
                        },
                        new
                        {
                            Id = 39,
                            Curso = "Backend Java",
                            NumModulo = 39,
                            Tipo = "Tarefa do módulo",
                            Valor = 15
                        },
                        new
                        {
                            Id = 40,
                            Curso = "Backend Java",
                            NumModulo = 40,
                            Tipo = "Tarefa do módulo",
                            Valor = 15
                        },
                        new
                        {
                            Id = 41,
                            Curso = "Backend Java",
                            NumModulo = 41,
                            Tipo = "Tarefa do módulo",
                            Valor = 15
                        },
                        new
                        {
                            Id = 42,
                            Curso = "Backend Java",
                            NumModulo = 42,
                            Tipo = "Tarefa do módulo",
                            Valor = 15
                        },
                        new
                        {
                            Id = 43,
                            Curso = "Backend Java",
                            NumModulo = 43,
                            Tipo = "Tarefa do módulo",
                            Valor = 15
                        },
                        new
                        {
                            Id = 44,
                            Curso = "Javascript",
                            NumModulo = 1,
                            Tipo = "Tarefa do módulo",
                            Valor = 15
                        },
                        new
                        {
                            Id = 45,
                            Curso = "Javascript",
                            NumModulo = 2,
                            Tipo = "Tarefa do módulo",
                            Valor = 15
                        },
                        new
                        {
                            Id = 46,
                            Curso = "Javascript",
                            NumModulo = 3,
                            Tipo = "Tarefa do módulo",
                            Valor = 15
                        },
                        new
                        {
                            Id = 47,
                            Curso = "Javascript",
                            NumModulo = 4,
                            Tipo = "Tarefa do módulo",
                            Valor = 15
                        },
                        new
                        {
                            Id = 48,
                            Curso = "Javascript",
                            NumModulo = 5,
                            Tipo = "Tarefa do módulo",
                            Valor = 15
                        },
                        new
                        {
                            Id = 49,
                            Curso = "Javascript",
                            NumModulo = 6,
                            Tipo = "Tarefa do módulo",
                            Valor = 15
                        },
                        new
                        {
                            Id = 50,
                            Curso = "Javascript",
                            NumModulo = 7,
                            Tipo = "Tarefa do módulo",
                            Valor = 18
                        },
                        new
                        {
                            Id = 51,
                            Curso = "Javascript",
                            NumModulo = 8,
                            Tipo = "Tarefa do módulo",
                            Valor = 15
                        },
                        new
                        {
                            Id = 52,
                            Curso = "Javascript",
                            NumModulo = 9,
                            Tipo = "Tarefa do módulo",
                            Valor = 15
                        },
                        new
                        {
                            Id = 53,
                            Curso = "Javascript",
                            NumModulo = 10,
                            Tipo = "Tarefa do módulo",
                            Valor = 18
                        },
                        new
                        {
                            Id = 54,
                            Curso = "Javascript",
                            NumModulo = 11,
                            Tipo = "Tarefa do módulo",
                            Valor = 15
                        },
                        new
                        {
                            Id = 55,
                            Curso = "Javascript",
                            NumModulo = 12,
                            Tipo = "Tarefa do módulo",
                            Valor = 15
                        },
                        new
                        {
                            Id = 56,
                            Curso = "Javascript",
                            NumModulo = 13,
                            Tipo = "Tarefa do módulo",
                            Valor = 15
                        },
                        new
                        {
                            Id = 57,
                            Curso = "Javascript",
                            NumModulo = 14,
                            Tipo = "Tarefa do módulo",
                            Valor = 15
                        },
                        new
                        {
                            Id = 58,
                            Curso = "Javascript",
                            NumModulo = 15,
                            Tipo = "Tarefa do módulo",
                            Valor = 15
                        },
                        new
                        {
                            Id = 59,
                            Curso = "Javascript",
                            NumModulo = 16,
                            Tipo = "Tarefa do módulo",
                            Valor = 15
                        },
                        new
                        {
                            Id = 60,
                            Curso = "Backend Java",
                            NumModulo = -1,
                            Tipo = "Fórum (Messages)",
                            Valor = 5
                        },
                        new
                        {
                            Id = 61,
                            Curso = "Javascript",
                            NumModulo = -1,
                            Tipo = "Fórum (Messages)",
                            Valor = 5
                        },
                        new
                        {
                            Id = 62,
                            Curso = "Backend Java",
                            NumModulo = -1,
                            Tipo = "Pergunta na tarefa do módulo",
                            Valor = 5
                        },
                        new
                        {
                            Id = 63,
                            Curso = "Javascript",
                            NumModulo = -1,
                            Tipo = "Pergunta na tarefa do módulo",
                            Valor = 5
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
