name: Deploy on Heroku

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
      
    - name: Heroku Action
      # You may pin to the exact commit or the version.
      # uses: CDNievas/heroku-action@c9cf9c85571e67583e44ec92c0d1113f66b0e838
      uses: CDNievas/heroku-action@v1.0
      with:
        # Used for authentication. You can find it in your heroku homepage account settings
        heroku_api_key: ${{ secrets.HEROKU_API }}
        # Email from Heroku Account
        heroku_email: $ {{ secrets.HEROKU_EMAIL }}
        # The appname to use for deploying/updating
        heroku_app_name: ${{ secrets.HEROKU_PROJ_NAME_CORRECOES_MGR_API }}
        # The branch that you would like to deploy to Heroku
        # branch: # optional, default is HEAD
        # Set this to true if want to use --force
        # useforce: # optional
        # Set if your app is located in a subdirectory.
        # appdir: # optional, default is 
        # Contents of the Procfile to save and deploy
        # procfile: # optional, default is 
        # Set to true if you need upload files generated dynamically by the GitHub Action to Heroku
        # dynamicFiles: # optional
        # Buildpacks to install on Heroku
        # buildpacks: # optional, default is 
        # Path to an localized env file
        # env_file: # optional, default is 
      
