name: Deploy on Heroku

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2    
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x        
    - name: Restore dependencies
      run: dotnet restore      
    - name: Build
      run: dotnet build --no-restore      
    - name: Test
      run: dotnet test --no-build --verbosity normal /p:CollectCoverage=true      
    - name: Deploy
      run: dotnet publish      
    - uses: akhileshns/heroku-deploy@v3.12.12 
      with:
        heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
        heroku_app_name: ${{ secrets.HEROKU_PROJ_NAME_CORRECOES_MGR_API }}
        heroku_email: ${{ secrets.HEROKU_EMAIL }}      
